version = 1

[streams]
[streams.webcam]
id = 'webcam'
name = 'webcam'
device = 'usb-0000:0a:00.1-5.1.1'
enabled = true
created_at = 2025-08-17T20:39:42.353888124-06:00
updated_at = 2025-08-17T20:39:42.353894105-06:00

[streams.webcam.ffmpeg]
input_format = 'mjpeg'
resolution = '1920x1080'
fps = '30'
encoder = 'h264_vaapi'
bitrate = '8000k'
global_args = ['-vaapi_device', '/dev/dri/renderD128']
video_filters = 'format=nv12,hwupload'
options = ['thread_queue_1024', 'copyts']

[streams.webcam.ffmpeg.encoder_params]
bf = '0'
qp = '20'
