[validation_info]
timestamp = '2025-08-16T00:05:11-06:00'
ffmpeg_version = '7.1.1'
test_duration = 2
test_resolution = '640x480'

[h264]
working = ['h264_vaapi', 'libx264']
failed = ['h264_nvenc', 'h264_amf', 'h264_qsv', 'h264_v4l2m2m', 'h264_vulkan']

[h265]
working = ['hevc_vaapi', 'libx265']
failed = ['hevc_nvenc', 'hevc_amf', 'hevc_qsv', 'hevc_v4l2m2m', 'hevc_vulkan']
